<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>co.com.crediya</groupId>
    <artifactId>autenticacion</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>

  <artifactId>reactive-web</artifactId>
  <packaging>jar</packaging>

  <name>reactive-web</name>
  <description>descripcion</description>

  <dependencies>

    <!-- Model Module -->
    <dependency>
      <groupId>co.com.crediya</groupId>
      <artifactId>model</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- UseCase Module -->
    <dependency>
      <groupId>co.com.crediya</groupId>
      <artifactId>usecase</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Spring Boot WebFlux -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>
    
    <!-- Spring Boot Validation -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <!-- Available at compile time, NOT included in JAR -->
      <scope>provided</scope>
    </dependency>


    <!-- Jakarta Validations (validation-api is the standard, hibernate-validator is the implementation) -->
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
    </dependency>

    <!-- MapStruct -->
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct-processor</artifactId>
      <optional>true</optional>
    </dependency>

  </dependencies>

</project>